// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: profile/v1/chart_data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListChartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ListChartRequest) Reset() {
	*x = ListChartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChartRequest) ProtoMessage() {}

func (x *ListChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChartRequest.ProtoReflect.Descriptor instead.
func (*ListChartRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{0}
}

func (x *ListChartRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ListChartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListChartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   []*ListChartResponse_Data `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListChartResponse) Reset() {
	*x = ListChartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChartResponse) ProtoMessage() {}

func (x *ListChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChartResponse.ProtoReflect.Descriptor instead.
func (*ListChartResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{1}
}

func (x *ListChartResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListChartResponse) GetData() []*ListChartResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type SaveChartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId   string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content    string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Symbol     string `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Resolution string `protobuf:"bytes,6,opt,name=resolution,proto3" json:"resolution,omitempty"`
}

func (x *SaveChartRequest) Reset() {
	*x = SaveChartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveChartRequest) ProtoMessage() {}

func (x *SaveChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveChartRequest.ProtoReflect.Descriptor instead.
func (*SaveChartRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{2}
}

func (x *SaveChartRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SaveChartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveChartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveChartRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveChartRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SaveChartRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

type SaveChartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id     uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SaveChartResponse) Reset() {
	*x = SaveChartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveChartResponse) ProtoMessage() {}

func (x *SaveChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveChartResponse.ProtoReflect.Descriptor instead.
func (*SaveChartResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{3}
}

func (x *SaveChartResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SaveChartResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SaveAsChartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId   string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChartId    uint32 `protobuf:"varint,3,opt,name=chart_id,json=chartId,proto3" json:"chart_id,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Content    string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Symbol     string `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Resolution string `protobuf:"bytes,7,opt,name=resolution,proto3" json:"resolution,omitempty"`
}

func (x *SaveAsChartRequest) Reset() {
	*x = SaveAsChartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveAsChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAsChartRequest) ProtoMessage() {}

func (x *SaveAsChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAsChartRequest.ProtoReflect.Descriptor instead.
func (*SaveAsChartRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{4}
}

func (x *SaveAsChartRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SaveAsChartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveAsChartRequest) GetChartId() uint32 {
	if x != nil {
		return x.ChartId
	}
	return 0
}

func (x *SaveAsChartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveAsChartRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveAsChartRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SaveAsChartRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

type SaveAsChartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SaveAsChartResponse) Reset() {
	*x = SaveAsChartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveAsChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAsChartResponse) ProtoMessage() {}

func (x *SaveAsChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAsChartResponse.ProtoReflect.Descriptor instead.
func (*SaveAsChartResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{5}
}

func (x *SaveAsChartResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LoadChartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChartId  uint32 `protobuf:"varint,3,opt,name=chart_id,json=chartId,proto3" json:"chart_id,omitempty"`
}

func (x *LoadChartRequest) Reset() {
	*x = LoadChartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadChartRequest) ProtoMessage() {}

func (x *LoadChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadChartRequest.ProtoReflect.Descriptor instead.
func (*LoadChartRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{6}
}

func (x *LoadChartRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LoadChartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoadChartRequest) GetChartId() uint32 {
	if x != nil {
		return x.ChartId
	}
	return 0
}

type LoadChartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *LoadChartResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LoadChartResponse) Reset() {
	*x = LoadChartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadChartResponse) ProtoMessage() {}

func (x *LoadChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadChartResponse.ProtoReflect.Descriptor instead.
func (*LoadChartResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{7}
}

func (x *LoadChartResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoadChartResponse) GetData() *LoadChartResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteChartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChartId  uint32 `protobuf:"varint,3,opt,name=chart_id,json=chartId,proto3" json:"chart_id,omitempty"`
}

func (x *DeleteChartRequest) Reset() {
	*x = DeleteChartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChartRequest) ProtoMessage() {}

func (x *DeleteChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChartRequest.ProtoReflect.Descriptor instead.
func (*DeleteChartRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteChartRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DeleteChartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteChartRequest) GetChartId() uint32 {
	if x != nil {
		return x.ChartId
	}
	return 0
}

type DeleteChartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteChartResponse) Reset() {
	*x = DeleteChartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChartResponse) ProtoMessage() {}

func (x *DeleteChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChartResponse.ProtoReflect.Descriptor instead.
func (*DeleteChartResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteChartResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListStudyTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ListStudyTemplateRequest) Reset() {
	*x = ListStudyTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStudyTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudyTemplateRequest) ProtoMessage() {}

func (x *ListStudyTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudyTemplateRequest.ProtoReflect.Descriptor instead.
func (*ListStudyTemplateRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{10}
}

func (x *ListStudyTemplateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ListStudyTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListStudyTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   []*ListStudyTemplateResponse_Data `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListStudyTemplateResponse) Reset() {
	*x = ListStudyTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStudyTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudyTemplateResponse) ProtoMessage() {}

func (x *ListStudyTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudyTemplateResponse.ProtoReflect.Descriptor instead.
func (*ListStudyTemplateResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{11}
}

func (x *ListStudyTemplateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListStudyTemplateResponse) GetData() []*ListStudyTemplateResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type SaveStudyTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content  string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SaveStudyTemplateRequest) Reset() {
	*x = SaveStudyTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveStudyTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStudyTemplateRequest) ProtoMessage() {}

func (x *SaveStudyTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStudyTemplateRequest.ProtoReflect.Descriptor instead.
func (*SaveStudyTemplateRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{12}
}

func (x *SaveStudyTemplateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SaveStudyTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveStudyTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveStudyTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SaveStudyTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SaveStudyTemplateResponse) Reset() {
	*x = SaveStudyTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveStudyTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStudyTemplateResponse) ProtoMessage() {}

func (x *SaveStudyTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStudyTemplateResponse.ProtoReflect.Descriptor instead.
func (*SaveStudyTemplateResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{13}
}

func (x *SaveStudyTemplateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LoadStudyTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChartId  uint32 `protobuf:"varint,3,opt,name=chart_id,json=chartId,proto3" json:"chart_id,omitempty"`
	Name     string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LoadStudyTemplateRequest) Reset() {
	*x = LoadStudyTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadStudyTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadStudyTemplateRequest) ProtoMessage() {}

func (x *LoadStudyTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadStudyTemplateRequest.ProtoReflect.Descriptor instead.
func (*LoadStudyTemplateRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{14}
}

func (x *LoadStudyTemplateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LoadStudyTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoadStudyTemplateRequest) GetChartId() uint32 {
	if x != nil {
		return x.ChartId
	}
	return 0
}

func (x *LoadStudyTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadStudyTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string                          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *LoadStudyTemplateResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LoadStudyTemplateResponse) Reset() {
	*x = LoadStudyTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadStudyTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadStudyTemplateResponse) ProtoMessage() {}

func (x *LoadStudyTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadStudyTemplateResponse.ProtoReflect.Descriptor instead.
func (*LoadStudyTemplateResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{15}
}

func (x *LoadStudyTemplateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoadStudyTemplateResponse) GetData() *LoadStudyTemplateResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteStudyTemplatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name     string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteStudyTemplatesRequest) Reset() {
	*x = DeleteStudyTemplatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStudyTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudyTemplatesRequest) ProtoMessage() {}

func (x *DeleteStudyTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudyTemplatesRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudyTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteStudyTemplatesRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DeleteStudyTemplatesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteStudyTemplatesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteStudyTemplatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteStudyTemplatesResponse) Reset() {
	*x = DeleteStudyTemplatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStudyTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudyTemplatesResponse) ProtoMessage() {}

func (x *DeleteStudyTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudyTemplatesResponse.ProtoReflect.Descriptor instead.
func (*DeleteStudyTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteStudyTemplatesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListChartResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp  uint32 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Symbol     string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Resolution string `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Id         uint32 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListChartResponse_Data) Reset() {
	*x = ListChartResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChartResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChartResponse_Data) ProtoMessage() {}

func (x *ListChartResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChartResponse_Data.ProtoReflect.Descriptor instead.
func (*ListChartResponse_Data) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListChartResponse_Data) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ListChartResponse_Data) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ListChartResponse_Data) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *ListChartResponse_Data) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListChartResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadChartResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp uint32 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id        uint32 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LoadChartResponse_Data) Reset() {
	*x = LoadChartResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadChartResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadChartResponse_Data) ProtoMessage() {}

func (x *LoadChartResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadChartResponse_Data.ProtoReflect.Descriptor instead.
func (*LoadChartResponse_Data) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{7, 0}
}

func (x *LoadChartResponse_Data) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LoadChartResponse_Data) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LoadChartResponse_Data) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadChartResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListStudyTemplateResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListStudyTemplateResponse_Data) Reset() {
	*x = ListStudyTemplateResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStudyTemplateResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudyTemplateResponse_Data) ProtoMessage() {}

func (x *ListStudyTemplateResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudyTemplateResponse_Data.ProtoReflect.Descriptor instead.
func (*ListStudyTemplateResponse_Data) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ListStudyTemplateResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadStudyTemplateResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *LoadStudyTemplateResponse_Data) Reset() {
	*x = LoadStudyTemplateResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_v1_chart_data_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadStudyTemplateResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadStudyTemplateResponse_Data) ProtoMessage() {}

func (x *LoadStudyTemplateResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_chart_data_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadStudyTemplateResponse_Data.ProtoReflect.Descriptor instead.
func (*LoadStudyTemplateResponse_Data) Descriptor() ([]byte, []int) {
	return file_profile_v1_chart_data_proto_rawDescGZIP(), []int{15, 0}
}

func (x *LoadStudyTemplateResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadStudyTemplateResponse_Data) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_profile_v1_chart_data_proto protoreflect.FileDescriptor

var file_profile_v1_chart_data_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68, 0x61,
	0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x48, 0x0a, 0x10, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0xe6, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x80, 0x01, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xae, 0x01, 0x0a,
	0x10, 0x53, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1e, 0x0a,
	0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a,
	0x11, 0x53, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0xcb, 0x01, 0x0a, 0x12, 0x53,
	0x61, 0x76, 0x65, 0x41, 0x73, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x72, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x72, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65,
	0x41, 0x73, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x63, 0x0a, 0x10, 0x4c, 0x6f, 0x61, 0x64, 0x43,
	0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x72, 0x74, 0x49, 0x64, 0x22, 0xc7, 0x01, 0x0a,
	0x11, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x62, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x65, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x72, 0x74, 0x49, 0x64, 0x22, 0x2d, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x50, 0x0a, 0x18,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8f,
	0x01, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x3e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x1a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x7e, 0x0a, 0x18, 0x53, 0x61, 0x76, 0x65, 0x53, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x33, 0x0a, 0x19, 0x53, 0x61, 0x76, 0x65, 0x53, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x7f, 0x0a, 0x18, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x75,
	0x64, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x72, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x72, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xa9, 0x01, 0x0a, 0x19, 0x4c, 0x6f, 0x61, 0x64, 0x53,
	0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3e, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x75, 0x64,
	0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x34, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x67, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64,
	0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x1c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x61, 0x72, 0x74, 0x76, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_profile_v1_chart_data_proto_rawDescOnce sync.Once
	file_profile_v1_chart_data_proto_rawDescData = file_profile_v1_chart_data_proto_rawDesc
)

func file_profile_v1_chart_data_proto_rawDescGZIP() []byte {
	file_profile_v1_chart_data_proto_rawDescOnce.Do(func() {
		file_profile_v1_chart_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_profile_v1_chart_data_proto_rawDescData)
	})
	return file_profile_v1_chart_data_proto_rawDescData
}

var file_profile_v1_chart_data_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_profile_v1_chart_data_proto_goTypes = []interface{}{
	(*ListChartRequest)(nil),               // 0: profile.v1.ListChartRequest
	(*ListChartResponse)(nil),              // 1: profile.v1.ListChartResponse
	(*SaveChartRequest)(nil),               // 2: profile.v1.SaveChartRequest
	(*SaveChartResponse)(nil),              // 3: profile.v1.SaveChartResponse
	(*SaveAsChartRequest)(nil),             // 4: profile.v1.SaveAsChartRequest
	(*SaveAsChartResponse)(nil),            // 5: profile.v1.SaveAsChartResponse
	(*LoadChartRequest)(nil),               // 6: profile.v1.LoadChartRequest
	(*LoadChartResponse)(nil),              // 7: profile.v1.LoadChartResponse
	(*DeleteChartRequest)(nil),             // 8: profile.v1.DeleteChartRequest
	(*DeleteChartResponse)(nil),            // 9: profile.v1.DeleteChartResponse
	(*ListStudyTemplateRequest)(nil),       // 10: profile.v1.ListStudyTemplateRequest
	(*ListStudyTemplateResponse)(nil),      // 11: profile.v1.ListStudyTemplateResponse
	(*SaveStudyTemplateRequest)(nil),       // 12: profile.v1.SaveStudyTemplateRequest
	(*SaveStudyTemplateResponse)(nil),      // 13: profile.v1.SaveStudyTemplateResponse
	(*LoadStudyTemplateRequest)(nil),       // 14: profile.v1.LoadStudyTemplateRequest
	(*LoadStudyTemplateResponse)(nil),      // 15: profile.v1.LoadStudyTemplateResponse
	(*DeleteStudyTemplatesRequest)(nil),    // 16: profile.v1.DeleteStudyTemplatesRequest
	(*DeleteStudyTemplatesResponse)(nil),   // 17: profile.v1.DeleteStudyTemplatesResponse
	(*ListChartResponse_Data)(nil),         // 18: profile.v1.ListChartResponse.Data
	(*LoadChartResponse_Data)(nil),         // 19: profile.v1.LoadChartResponse.Data
	(*ListStudyTemplateResponse_Data)(nil), // 20: profile.v1.ListStudyTemplateResponse.Data
	(*LoadStudyTemplateResponse_Data)(nil), // 21: profile.v1.LoadStudyTemplateResponse.Data
}
var file_profile_v1_chart_data_proto_depIdxs = []int32{
	18, // 0: profile.v1.ListChartResponse.data:type_name -> profile.v1.ListChartResponse.Data
	19, // 1: profile.v1.LoadChartResponse.data:type_name -> profile.v1.LoadChartResponse.Data
	20, // 2: profile.v1.ListStudyTemplateResponse.data:type_name -> profile.v1.ListStudyTemplateResponse.Data
	21, // 3: profile.v1.LoadStudyTemplateResponse.data:type_name -> profile.v1.LoadStudyTemplateResponse.Data
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_profile_v1_chart_data_proto_init() }
func file_profile_v1_chart_data_proto_init() {
	if File_profile_v1_chart_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_profile_v1_chart_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveChartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveChartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveAsChartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveAsChartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadChartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadChartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStudyTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStudyTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveStudyTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveStudyTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadStudyTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadStudyTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStudyTemplatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStudyTemplatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChartResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadChartResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStudyTemplateResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_v1_chart_data_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadStudyTemplateResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_profile_v1_chart_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profile_v1_chart_data_proto_goTypes,
		DependencyIndexes: file_profile_v1_chart_data_proto_depIdxs,
		MessageInfos:      file_profile_v1_chart_data_proto_msgTypes,
	}.Build()
	File_profile_v1_chart_data_proto = out.File
	file_profile_v1_chart_data_proto_rawDesc = nil
	file_profile_v1_chart_data_proto_goTypes = nil
	file_profile_v1_chart_data_proto_depIdxs = nil
}
