// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChartsColumns holds the columns for the "charts" table.
	ChartsColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString, Default: ""},
		{Name: "chart_id", Type: field.TypeUint32, Nullable: true},
		{Name: "template_id", Type: field.TypeString, Default: ""},
		{Name: "client_id", Type: field.TypeString, Default: ""},
		{Name: "type", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "content", Type: field.TypeString, Default: ""},
		{Name: "symbol", Type: field.TypeString, Default: ""},
		{Name: "resolution", Type: field.TypeString, Default: ""},
	}
	// ChartsTable holds the schema information for the "charts" table.
	ChartsTable = &schema.Table{
		Name:       "charts",
		Columns:    ChartsColumns,
		PrimaryKey: []*schema.Column{ChartsColumns[0]},
	}
	// ProfilesColumns holds the columns for the "profiles" table.
	ProfilesColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "full_name", Type: field.TypeString, Default: ""},
		{Name: "email", Type: field.TypeString},
		{Name: "email_confirmed_at", Type: field.TypeTime},
		{Name: "phone", Type: field.TypeString},
		{Name: "phone_confirmed_at", Type: field.TypeTime},
		{Name: "language", Type: field.TypeString, Default: "en"},
		{Name: "is_sso_user", Type: field.TypeBool, Default: false},
	}
	// ProfilesTable holds the schema information for the "profiles" table.
	ProfilesTable = &schema.Table{
		Name:       "profiles",
		Columns:    ProfilesColumns,
		PrimaryKey: []*schema.Column{ProfilesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChartsTable,
		ProfilesTable,
	}
)

func init() {
}
