// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/nartvt/profile-service/ent/chart"
	"github.com/nartvt/profile-service/ent/profile"
	"github.com/nartvt/profile-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chartMixin := schema.Chart{}.Mixin()
	chartMixinFields0 := chartMixin[0].Fields()
	_ = chartMixinFields0
	chartFields := schema.Chart{}.Fields()
	_ = chartFields
	// chartDescCreatedAt is the schema descriptor for created_at field.
	chartDescCreatedAt := chartMixinFields0[0].Descriptor()
	// chart.DefaultCreatedAt holds the default value on creation for the created_at field.
	chart.DefaultCreatedAt = chartDescCreatedAt.Default.(func() time.Time)
	// chartDescUpdatedAt is the schema descriptor for updated_at field.
	chartDescUpdatedAt := chartMixinFields0[1].Descriptor()
	// chart.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chart.DefaultUpdatedAt = chartDescUpdatedAt.Default.(func() time.Time)
	// chart.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chart.UpdateDefaultUpdatedAt = chartDescUpdatedAt.UpdateDefault.(func() time.Time)
	// chartDescUserID is the schema descriptor for user_id field.
	chartDescUserID := chartFields[1].Descriptor()
	// chart.DefaultUserID holds the default value on creation for the user_id field.
	chart.DefaultUserID = chartDescUserID.Default.(string)
	// chartDescTemplateID is the schema descriptor for template_id field.
	chartDescTemplateID := chartFields[3].Descriptor()
	// chart.DefaultTemplateID holds the default value on creation for the template_id field.
	chart.DefaultTemplateID = chartDescTemplateID.Default.(string)
	// chartDescClientID is the schema descriptor for client_id field.
	chartDescClientID := chartFields[4].Descriptor()
	// chart.DefaultClientID holds the default value on creation for the client_id field.
	chart.DefaultClientID = chartDescClientID.Default.(string)
	// chartDescType is the schema descriptor for type field.
	chartDescType := chartFields[5].Descriptor()
	// chart.DefaultType holds the default value on creation for the type field.
	chart.DefaultType = chartDescType.Default.(string)
	// chartDescName is the schema descriptor for name field.
	chartDescName := chartFields[6].Descriptor()
	// chart.DefaultName holds the default value on creation for the name field.
	chart.DefaultName = chartDescName.Default.(string)
	// chartDescContent is the schema descriptor for content field.
	chartDescContent := chartFields[7].Descriptor()
	// chart.DefaultContent holds the default value on creation for the content field.
	chart.DefaultContent = chartDescContent.Default.(string)
	// chartDescSymbol is the schema descriptor for symbol field.
	chartDescSymbol := chartFields[8].Descriptor()
	// chart.DefaultSymbol holds the default value on creation for the symbol field.
	chart.DefaultSymbol = chartDescSymbol.Default.(string)
	// chartDescResolution is the schema descriptor for resolution field.
	chartDescResolution := chartFields[9].Descriptor()
	// chart.DefaultResolution holds the default value on creation for the resolution field.
	chart.DefaultResolution = chartDescResolution.Default.(string)
	// chartDescID is the schema descriptor for id field.
	chartDescID := chartFields[0].Descriptor()
	// chart.DefaultID holds the default value on creation for the id field.
	chart.DefaultID = chartDescID.Default.(func() uuid.UUID)
	profileMixin := schema.Profile{}.Mixin()
	profileMixinFields0 := profileMixin[0].Fields()
	_ = profileMixinFields0
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescCreatedAt is the schema descriptor for created_at field.
	profileDescCreatedAt := profileMixinFields0[0].Descriptor()
	// profile.DefaultCreatedAt holds the default value on creation for the created_at field.
	profile.DefaultCreatedAt = profileDescCreatedAt.Default.(func() time.Time)
	// profileDescUpdatedAt is the schema descriptor for updated_at field.
	profileDescUpdatedAt := profileMixinFields0[1].Descriptor()
	// profile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profile.DefaultUpdatedAt = profileDescUpdatedAt.Default.(func() time.Time)
	// profile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	profile.UpdateDefaultUpdatedAt = profileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// profileDescFullName is the schema descriptor for full_name field.
	profileDescFullName := profileFields[2].Descriptor()
	// profile.DefaultFullName holds the default value on creation for the full_name field.
	profile.DefaultFullName = profileDescFullName.Default.(string)
	// profileDescLanguage is the schema descriptor for language field.
	profileDescLanguage := profileFields[7].Descriptor()
	// profile.DefaultLanguage holds the default value on creation for the language field.
	profile.DefaultLanguage = profileDescLanguage.Default.(string)
	// profileDescIsSSOUser is the schema descriptor for is_sso_user field.
	profileDescIsSSOUser := profileFields[8].Descriptor()
	// profile.DefaultIsSSOUser holds the default value on creation for the is_sso_user field.
	profile.DefaultIsSSOUser = profileDescIsSSOUser.Default.(bool)
	// profileDescID is the schema descriptor for id field.
	profileDescID := profileFields[0].Descriptor()
	// profile.DefaultID holds the default value on creation for the id field.
	profile.DefaultID = profileDescID.Default.(func() uuid.UUID)
}
