// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/nartvt/go-core/conf"
	"github.com/nartvt/go-core/server"
	"github.com/nartvt/go-core/service"
	"github.com/nartvt/profile-service/internal/biz"
	conf2 "github.com/nartvt/profile-service/internal/conf"
	"github.com/nartvt/profile-service/internal/data"
	service2 "github.com/nartvt/profile-service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf2.Data, logger log.Logger) (service.Service, func(), error) {
	httpServer := server.NewHTTPServer(confServer, logger)
	grpcServer := server.NewGRPCServer(confServer, logger)
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	chartRepo := data.NewChartRepo(dataData)
	chartUsecase := biz.NewChartUsecase(chartRepo)
	chartService := service2.NewChartService(chartUsecase)
	profileRepo := data.NewProfileRepo(dataData)
	profileUsecase := biz.NewProfileUsecase(profileRepo)
	profileService := service2.NewProfileService(profileUsecase)
	serviceService := initService(logger, httpServer, grpcServer, chartService, profileService)
	return serviceService, func() {
		cleanup()
	}, nil
}
