// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chart is the predicate function for chart builders.
type Chart func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)
